name: DailyStreamingScraper livesportsontv

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install curl_cffi pycountry beautifulsoup4 lxml playwright
          python -m playwright install --with-deps chromium
          
      - name: Run script
        run: python DailyStreamingScraperFootballV2.py
        
      - name: Run wheresthematch
        run: python wheresthematch_scraper.py  

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update livesportsontv.json & wheresthematch.json"
