name: Euro VN Schedule SofaScore (24h tới)

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install curl_cffi pycountry beautifulsoup4 lxml playwright
          playwright install chromium

      - name: Run script
        run: python euro_vn_full_schedule_live.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add schedule.json live_schedule.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update schedule.json + live_schedule.m3u (SofaScore + WTM)"
          git pull --rebase origin ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
